export * from "./types/mail.entity";
export * from "./data/mock-data";
export { useMailStore } from "./store/use-mail-store";
export { MailClient } from "./components/MailClient";
export { MailNav } from "./components/MailNav";
export { MailList } from "./components/MailList";
export { MailDisplay } from "./components/MailDisplay";
export { NavItem } from "./components/NavItem";
export { AccountSwitcher } from "./components/AccountSwitcher";
export * from "./config/email-icon-registry";
export { MailIconSettingsDialog } from "./components/MailIconSettingsDialog";
